#!/bin/sh

# Display all PostgreSQL databases with tablespaces with psql -l like formatting. Also displays the pg_default tablespace location
#
# smattila, 2012

echo ""
echo "PostgreSQL :: databases and tablespaces"
psql -d postgres -c  "SELECT d.datname as Name,r.rolname as Owner, pg_catalog.pg_encoding_to_char(d.encoding) as Encoding,pg_catalog.shobj_description(d.oid, 'pg_database') as Description,t.spcname as Tablespace FROM pg_catalog.pg_database d JOIN pg_catalog.pg_roles r ON d.datdba = r.oid JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid ORDER BY t.spcname;"
echo ""
echo "PostgreSQL :: data_directory (pg_default) location"
psql -d postgres -c "SHOW data_directory;"
echo ""
